# Generated by Django 5.0.6 on 2024-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, default='banner.png', upload_to='')),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
    ]
